- hosts: tarball

  tasks:
  - name: install gcc
    yum:
     name: gcc
     state: latest
  
  - name: create group
    group:
     name: weareweb-ulululu
     state: present

  - name: create user
    user:
     name: dhika-web
     shell: /bin/false
     group: weareweb-ulululu

  - name: create folder
    file:
     path: /var/www
     state: directory
     owner: dhika-web
     group: weareweb-ulululu
     mode: 0644

  - name: create folder again
    file:
     path: /usr/local/src
     state: directory

  - name: create php folder
    file:
     path: /opt/php-7.2.7
     state: directory

  - name: unarchive php
    unarchive:
     src: http://us.php.net/get/php-7.2.7.tar.bz2/from/this/mirror
     dest: /usr/local/src
     remote_src: yes

  - name: install dependecies php
    yum:
     name: "{{ item }}"
     state: latest
    with_items:
     - libxml2
     - libxml2-devel

  - name: konfigurasi installer
    command: "{{ item }}"
    args:
     chdir: /usr/local/src/php-7.2.7
    with_items:
     - ./configure --prefix=/opt/php-7.2.7 --enable-fpm --enable-opcache
     - make
     - make install

  - name: copy file konfig
    copy: src=php.ini dest=/opt/php-7.2.7/lib/php.ini

  - name: copy file konfig lagi
    copy: src=php-fpm.conf dest=/opt/php-7.2.7/etc/php-fpm.conf

  - name: start php-fpm
    command: /opt/php-7.2.7/sbin/php-fpm --fpm-config /opt/php-7.2.7/etc/php-fpm.conf    
