- hosts: webserver
  tasks:
  - name: install epel-repo
    yum:
     name: epel-release
     state: latest

  - name: install nginx
    yum:
     name: nginx
     state: latest

  - name: nyalain webnya
    service: name=nginx state=running enabled=true

  - name: nyalain tembokapi
    service: name=firewalld state=running enabled=true

  - name: tambahin akses port
    firewalld:
     service: http
     permanent: true
     state: enabled

  - name: restart webnya
    service: name=nginx state=restarted

  - name: restart tembokapi
    service: name=firewalld state=reloaded

  - name: copy folder
    copy: src=index.html dest=/usr/share/nginx/html/index.html

  - name: restart lagi webnya
    service: name=nginx state=restarted
